import type { PluralizeRule } from './types';

export const irregularRules: [string, string][] = [
	// Pronouns
	['I', 'we'],
	['me', 'us'],
	['he', 'they'],
	['she', 'they'],
	['them', 'them'],
	['myself', 'ourselves'],
	['yourself', 'yourselves'],
	['itself', 'themselves'],
	['herself', 'themselves'],
	['himself', 'themselves'],
	['themself', 'themselves'],
	['is', 'are'],
	['was', 'were'],
	['has', 'have'],
	['this', 'these'],
	['that', 'those'],
	['my', 'our'],
	['its', 'their'],
	['his', 'their'],
	['her', 'their'],

	// Common irregulars
	['child', 'children'],
	['person', 'people'],
	['man', 'men'],
	['woman', 'women'],
	['tooth', 'teeth'],
	['foot', 'feet'],
	['mouse', 'mice'],
	['goose', 'geese'],
	['ox', 'oxen'],
	['leaf', 'leaves'],
	['datum', 'data'],
	['medium', 'media'],
	['analysis', 'analyses'],
	['diagnosis', 'diagnoses'],
	['basis', 'bases'],
	['thesis', 'theses'],
	['crisis', 'crises'],
	['phenomenon', 'phenomena'],
	['criterion', 'criteria'],
	['index', 'indices'],
	['matrix', 'matrices'],
	['vertex', 'vertices'],
	['quiz', 'quizzes'],
];

export const pluralRules: PluralizeRule[] = [
	[/s?$/i, 's'],
	// [/([^\u0000-\u007F])$/i, '$1'],
	[/([^aeiou]ese)$/i, '$1'],
	[/(ax|test)is$/i, '$1es'],
	[/(alias|[^aou]us|t[lm]as|gas|ris)$/i, '$1es'],
	[/(e[mn]u)s?$/i, '$1s'],
	[/([^l]ias|[aeiou]las|[ejzr]as|[iu]am)$/i, '$1'],
	[
		/(alumn|syllab|vir|radi|nucle|fung|cact|stimul|termin|bacill|foc|uter|loc|strat)(?:us|i)$/i,
		'$1i',
	],
	[/(alumn|alg|vertebr)(?:a|ae)$/i, '$1ae'],
	[/(seraph|cherub)(?:im)?$/i, '$1im'],
	[/(her|at|gr)o$/i, '$1oes'],
	[/sis$/i, 'ses'],
	[/(?:(kni|wi|li)fe|(ar|l|ea|eo|oa|hoo)f)$/i, '$1$2ves'],
	[/([^aeiouy]|qu)y$/i, '$1ies'],
	[/(x|ch|ss|sh|zz)$/i, '$1es'],
	[/(matr|cod|mur|sil|vert|ind|append)(?:ix|ex)$/i, '$1ices'],
	[/\b((?:tit)?m|l)(?:ice|ouse)$/i, '$1ice'],
	[/(pe)(?:rson|ople)$/i, '$1ople'],
	[/(child)(?:ren)?$/i, '$1ren'],
	[/eaux$/i, '$0'],
	[/m[ae]n$/i, 'men'],
];

export const uncountableWords = new Set([
	'aircraft',
	'alcohol',
	'ammo',
	'analytics',
	'anime',
	'athletics',
	'audio',
	'bison',
	'blood',
	'butter',
	'cash',
	'chess',
	'clothing',
	'commerce',
	'cooperation',
	'corps',
	'debris',
	'diabetes',
	'energy',
	'equipment',
	'fish',
	'furniture',
	'gas',
	'gold',
	'hardware',
	'headquarters',
	'health',
	'homework',
	'housework',
	'information',
	'insurance',
	'jewelry',
	'knowledge',
	'livestock',
	'luck',
	'machinery',
	'metadata',
	'money',
	'music',
	'news',
	'poetry',
	'pollution',
	'research',
	'rice',
	'series',
	'sheep',
	'software',
	'species',
	'staff',
	'traffic',
	'transportation',
	'weather',
	'wildlife',
	'you',
]);
