import type { PluralizeRule } from './types';

export const irregularRules: readonly [string, string][] =
	/* @__PURE__ */ Object.freeze([
		// Pronouns
		['I', 'we'],
		['me', 'us'],
		['he', 'they'],
		['she', 'they'],
		['them', 'them'],
		['myself', 'ourselves'],
		['yourself', 'yourselves'],
		['itself', 'themselves'],
		['herself', 'themselves'],
		['himself', 'themselves'],
		['themself', 'themselves'],
		['is', 'are'],
		['was', 'were'],
		['has', 'have'],
		['this', 'these'],
		['that', 'those'],
		['my', 'our'],
		['its', 'their'],
		['his', 'their'],
		['her', 'their'],

		// Common irregulars
		['child', 'children'],
		['person', 'people'],
		['man', 'men'],
		['woman', 'women'],
		['tooth', 'teeth'],
		['foot', 'feet'],
		['mouse', 'mice'],
		['goose', 'geese'],
		['ox', 'oxen'],
		['leaf', 'leaves'],
		['datum', 'data'],
		['medium', 'media'],
		['analysis', 'analyses'],
		['diagnosis', 'diagnoses'],
		['basis', 'bases'],
		['thesis', 'theses'],
		['crisis', 'crises'],
		['phenomenon', 'phenomena'],
		['criterion', 'criteria'],
		['index', 'indices'],
		['matrix', 'matrices'],
		['vertex', 'vertices'],
		['quiz', 'quizzes'],
		['die', 'dice'],
		['yes', 'yeses'],
		['human', 'humans'],
		['proof', 'proofs'],
		['carve', 'carves'],
		['valve', 'valves'],
		['looey', 'looies'],
		['thief', 'thieves'],
		['groove', 'grooves'],
		['pickaxe', 'pickaxes'],
		['passerby', 'passersby'],

		// Words ending in with a consonant and `o`.
		['echo', 'echoes'],
		['dingo', 'dingoes'],
		['mango', 'mangoes'],
		['volcano', 'volcanoes'],
		['tornado', 'tornadoes'],
		['torpedo', 'torpedoes'],
		// Ends with `us`.
		['genus', 'genera'],
		['viscus', 'viscera'],
		// Ends with `ma`.
		['stigma', 'stigmata'],
		['stoma', 'stomata'],
		['dogma', 'dogmata'],
		['lemma', 'lemmata'],
		['schema', 'schemata'],
		['anathema', 'anathemata'],
	]);

export const pluralRules: readonly PluralizeRule[] =
	/* @__PURE__ */ Object.freeze([
		[/s?$/i, 's'],
		// [/([^\u0000-\u007F])$/i, '$1'],
		[/([^aeiou]ese)$/i, '$1'],
		[/(ax|test)is$/i, '$1es'],
		[/(alias|[^aou]us|t[lm]as|gas|ris)$/i, '$1es'],
		[/(e[mn]u)s?$/i, '$1s'],
		[/([^l]ias|[aeiou]las|[ejzr]as|[iu]am)$/i, '$1'],
		[
			/(alumn|syllab|vir|radi|nucle|fung|cact|stimul|termin|bacill|foc|uter|loc|strat)(?:us|i)$/i,
			'$1i',
		],
		[/(alumn|alg|vertebr)(?:a|ae)$/i, '$1ae'],
		[/(seraph|cherub)(?:im)?$/i, '$1im'],
		[/(her|at|gr)o$/i, '$1oes'],
		[/sis$/i, 'ses'],
		[/(?:(kni|wi|li)fe|(ar|l|ea|eo|oa|hoo)f)$/i, '$1$2ves'],
		[/([^aeiouy]|qu)y$/i, '$1ies'],
		[/(x|ch|ss|sh|zz)$/i, '$1es'],
		[/(matr|cod|mur|sil|vert|ind|append)(?:ix|ex)$/i, '$1ices'],
		[/\b((?:tit)?m|l)(?:ice|ouse)$/i, '$1ice'],
		[/(pe)(?:rson|ople)$/i, '$1ople'],
		[/(child)(?:ren)?$/i, '$1ren'],
		[/eaux$/i, '$0'],
		[/m[ae]n$/i, 'men'],
	]);

export const uncountables = /* @__PURE__ */ Object.freeze(
	new Set([
		'aircraft',
		'alcohol',
		'ammo',
		'analytics',
		'anime',
		'athletics',
		'audio',
		'bison',
		'blood',
		'butter',
		'cash',
		'chess',
		'clothing',
		'commerce',
		'cooperation',
		'corps',
		'debris',
		'diabetes',
		'energy',
		'equipment',
		'furniture',
		'gas',
		'gold',
		'hardware',
		'headquarters',
		'health',
		'homework',
		'housework',
		'information',
		'insurance',
		'jewelry',
		'knowledge',
		'livestock',
		'luck',
		'machinery',
		'metadata',
		'money',
		'music',
		'news',
		'poetry',
		'pollution',
		'research',
		'rice',
		'series',
		'software',
		'species',
		'staff',
		'traffic',
		'transportation',
		'weather',
		'wildlife',
		'you',

		'access',
		'accommodation',
		'adulthood',
		'advertising',
		'advice',
		'aggression',
		'aid',
		'air',
		'anger',
		'applause',
		'arithmetic',
		'assistance',
		'attention',
		'bacon',
		'beauty',
		'beef',
		'biology',
		'botany',
		'bread',
		'carbon',
		'cardboard',
		'chalk',
		'chaos',
		'cheese',
		'childhood',
		'coal',
		'coffee',
		'compassion',
		'comprehension',
		'corruption',
		'cotton',
		'courage',
		'currency',
		'damage',
		'dancing',
		'danger',
		'delight',
		'dessert',
		'dignity',
		'dirt',
		'distribution',
		'dust',
		'economics',
		'education',
		'electricity',
		'employment',
		'engineering',
		'enjoyment',
		'entertainment',
		'envy',
		'ethics',
		'evidence',
		'evolution',
		'failure',
		'faith',
		'fame',
		'fiction',
		'flour',
		'flu',
		'food',
		'freedom',
		'fruit',
		'fuel',
		'fun',
		'garbage',
		'garlic',
		'genetics',
		'glass',
		'golf',
		'gossip',
		'grammar',
		'grass',
		'gratitude',
		'grief',
		'ground',
		'guilt',
		'gymnastics',
		'hair',
		'happiness',
		'harm',
		'hate',
		'hatred',
		'heat',
		'height',
		'help',
		'honesty',
		'honey',
		'hospitality',
		'humor',
		'humour',
		'hunger',
		'hydrogen',
		'ice',
		'ice-cream',
		'ice cream',
		'importance',
		'inflation',
		'injustice',
		'innocence',
		'intelligence',
		'iron',
		'irony',
		'jam',
		'jealousy',
		'jelly',
		'joy',
		'judo',
		'justice',
		'karate',
		'kindness',
		'labour',
		'lack',
		'land',
		'laughter',
		'lava',
		'leather',
		'leisure',
		'lightning',
		'linguistics',
		'literature',
		'litter',
		'logic',
		'loneliness',
		'love',
		'luggage',
		'magic',
		'mail',
		'management',
		'mankind',
		'marble',
		'mathematics',
		'mayonnaise',
		'measles',
		'meat',
		'metal',
		'methane',
		'milk',
		'mud',
		'nature',
		'nitrogen',
		'nonsense',
		'nurture',
		'nutrition',
		'obedience',
		'obesity',
		'oil',
		'oxygen',
		'passion',
		'pasta',
		'patience',
		'permission',
		'physics',
		'poverty',
		'power',
		'pride',
		'production',
		'progress',
		'pronunciation',
		'psychology',
		'publicity',
		'punctuation',
		'quality',
		'quantity',
		'quartz',
		'racism',
		'rain',
		'recreation',
		'relaxation',
		'reliability',
		'research',
		'respect',
		'revenge',
		'rubbish',
		'rum',
		'safety',
		'salad',
		'salt',
		'sand',
		'satire',
		'scenery',
		'seafood',
		'seaside',
		'shame',
		'shopping',
		'silence',
		'sleep',
		'smoke',
		'smoking',
		'snow',
		'soap',
		'soil',
		'sorrow',
		'soup',
		'speed',
		'spelling',
		'sport',
		'steam',
		'strength',
		'stuff',
		'stupidity',
		'success',
		'sugar',
		'sunshine',
		'symmetry',
		'tea',
		'tennis',
		'thirst',
		'thunder',
		'timber',
		'toast',
		'tolerance',
		'trade',
		'travel',
		'trust',
		'understanding',
		'underwear',
		'unemployment',
		'unity',
		'usage',
		'validity',
		'veal',
		'vegetation',
		'vegetarianism',
		'vengeance',
		'violence',
		'vision',
		'vitality',
		'warmth',
		'water',
		'wealth',
		'weight',
		'welfare',
		'wheat',
		'whiskey',
		'width',
		'wine',
		'wisdom',
		'wool',
		'yeast',
		'yoga',
		'youth',
		'zinc',
		'zoology',

		// RegEx(es)
		/pok[eé]mon$/i,
		/[^aeiou]ese$/i,
		/deer$/i,
		/fish$/i,
		/measles$/i,
		/o[iu]s$/i,
		/pox$/i,
		/sheep$/i,
		/scissors$/i,
		/glasses$/i,
		/pants$/i,
		/shorts$/i,
		/trousers$/i,
		/jeans$/i,
	])
);
