export const UNIT_MAP = {
	time: [
		'nanosecond',
		'microsecond',
		'millisecond',
		'second',
		'minute',
		'hour',
		'day',
		'week',
		'month',
		'year',
		'decade',
		'century',
		'millennium',
	],
	length: ['meter', 'kilometer', 'mile', 'inch'],
	data: ['byte', 'kilobyte', 'megabyte', 'gigabyte'],
	temp: ['celsius', 'fahrenheit', 'kelvin'],
} as const;
