import type { UTCOffSet } from './types';

/** List of time-zones with respective time-zone offsets (in minutes) as object (`{timeZone: offset}`) */
export const TIME_ZONES = /* @__PURE__ */ Object.freeze({
	// ! UTC -12:00 to -01:00 (Mostly Pacific Islands, Americas)
	/** International Date Line West (Baker Island, Howland Island) */
	IDLW: -12 * 60,
	/** Baker Island Time (Uninhabited) */
	BIT: -12 * 60,
	/** Samoa Standard Time (American Samoa, Midway) */
	SST: -11 * 60,
	/** Niue Time */
	NUT: -11 * 60,
	/** Hawaii-Aleutian Standard Time (USA-Hawaii) */
	HST: -10 * 60,
	/** Cook Island Time */
	CKT: -10 * 60,
	/** Tahiti Time (French Polynesia) */
	TAHT: -10 * 60,
	/** Alaska Standard Time (USA-Alaska) */
	AKST: -9 * 60,
	/** Gambier Time (French Polynesia) */
	GAMT: -9 * 60,
	/** Paraguay Time (Summer UTC-3) */
	PYT: -9 * 60,
	/** Marquesas Islands Time (UTC−09:30) */
	MART: -9.5 * 60,
	/** Hawaii-Aleutian Daylight Time (USA-Hawaii, DST) */
	HDT: -9 * 60,
	/** Pacific Standard Time (USA-West Coast, Canada) */
	PST: -8 * 60,
	/** Alaska Daylight Time (USA-Alaska, DST) */
	AKDT: -8 * 60,
	/** Mountain Standard Time (USA/Canada Rockies) */
	MST: -7 * 60,
	/** Mountain Daylight Time (USA/Canada Rockies, DST) */
	MDT: -6 * 60,
	/** Pacific Daylight Time (USA-West Coast, Canada, DST) */
	PDT: -7 * 60,
	/** Central Standard Time (USA/Canada Central) */
	CST: -6 * 60,
	/** Central Daylight Time (USA/Canada Central, DST) */
	CDT: -5 * 60,
	/** Easter Island Time (Chile) */
	EAST: -6 * 60,
	/** Eastern Standard Time (USA/Canada East Coast) */
	EST: -5 * 60,
	/** Eastern Daylight Time (USA/Canada East Coast, DST) */
	EDT: -4 * 60,
	/** Peru Time */
	PET: -5 * 60,
	/** Colombia Time */
	COT: -5 * 60,
	/** Acre Time (Brazil-West) */
	ACT: -5 * 60,
	/** Atlantic Standard Time (Canada-Maritime, Caribbean) */
	'AST-Atlantic': -4 * 60,
	/** Bolivia Time */
	BOT: -4 * 60,
	/** Venezuelan Standard Time */
	VET: -4 * 60,
	/** Guyana Time */
	GYT: -4 * 60,
	/** Chile Standard Time */
	CLT: -4 * 60,
	/** Atlantic Daylight Time (Canada-Maritime, DST) */
	ADT: -3 * 60,
	/** Brasília Time (Brazil-East) */
	BRT: -3 * 60,
	/** Argentina Time */
	ART: -3 * 60,
	/** Uruguay Time */
	UYT: -3 * 60,
	/** Falkland Islands Summer Time */
	FKST: -3 * 60,
	/** Saint Pierre and Miquelon Standard Time */
	PMST: -3 * 60,
	/** Chile Summer Time (DST) */
	CLST: -3 * 60,
	/** French Guiana Time */
	GFT: -3 * 60,
	/** Newfoundland Standard Time */
	NST: -3.5 * 60,
	/** Newfoundland Daylight Time (DST) */
	NDT: -2.5 * 60,
	/** Fernando de Noronha Time (Brazil) */
	FNT: -2 * 60,
	/** South Georgia Time */
	'GST-South Georgia': -2 * 60,
	/** Brazil Summer Time (DST) */
	BRST: -2 * 60,
	/** Azores Time (Portugal) */
	AZOT: -1 * 60,
	/** Cape Verde Time */
	CVT: -1 * 60,

	// ! UTC ±00:00 (Europe, Africa, Greenland)
	/** Greenwich Mean Time (UK, Iceland, West Africa) */
	GMT: 0,
	/** Coordinated Universal Time */
	UTC: 0,
	/** Western European Time (Portugal, Morocco) */
	WET: 0,
	/** Eastern Greenland Summer Time */
	EGST: 0,
	/** Central European Time (France, Germany, Italy) */
	CET: 1 * 60,
	/** West Africa Time (Nigeria, Algeria) */
	WAT: 1 * 60,
	/** Middle European Time (Historical) */
	MET: 1 * 60,
	/** Western European Summer Time (Summer UTC+1) */
	WEST: 1 * 60,
	/** British Summer Time (UK DST) */
	'BST-UK': 1 * 60,
	/** Central European Summer Time (DST) */
	CEST: 2 * 60,
	/** Middle European Summer Time (DST) */
	MEST: 2 * 60,

	// ! UTC +02:00 to +05:00 (Europe, Africa, Middle East, Russia)
	/** Eastern European Time (Greece, Finland, Egypt) */
	EET: 2 * 60,
	/** Central Africa Time (Sudan, South Africa) */
	CAT: 2 * 60,
	/** South Africa Standard Time */
	SAST: 2 * 60,
	/** Israel Standard Time */
	'IST-ISRAEL': 2 * 60,
	/** Israel Daylight Time (DST) */
	'IST-DST': 3 * 60,
	/** Eastern European Summer Time */
	EEST: 3 * 60,
	/** Moscow Time (Russia-West) */
	MSK: 3 * 60,
	/** Syowa Time (Antarctica) */
	SYOT: 3 * 60,
	/** Arabia Standard Time (Iraq, Saudi Arabia) */
	'AST-ARAB': 3 * 60,
	/** East Africa Time (Kenya, Ethiopia) */
	EAT: 3 * 60,
	/** Iran Standard Time */
	IRST: 3.5 * 60,
	/** Iran Daylight Time (DST) */
	IRDT: 4.5 * 60,
	/** Armenia Time */
	AMT: 4 * 60,
	/** Georgia Time */
	GET: 4 * 60,
	/** Azerbaijan Time */
	AZT: 4 * 60,
	/** Mauritius Time */
	MUT: 4 * 60,
	/** Seychelles Time */
	SCT: 4 * 60,
	/** Gulf Standard Time (UAE, Oman) */
	'GST-GULF': 4 * 60,
	/** Samara Time (Russia) */
	SAMT: 4 * 60,
	/** Pakistan Standard Time */
	PKT: 5 * 60,
	/** Tajikistan Time */
	TJT: 5 * 60,
	/** Turkmenistan Time */
	TMT: 5 * 60,
	/** Uzbekistan Time */
	UZT: 5 * 60,
	/** Aqtobe Time (Kazakhstan) */
	AQTT: 5 * 60,
	/** Yekaterinburg Time (Russia) */
	YEKT: 5 * 60,
	/** Yekaterinburg Summer Time (Russia, DST) */
	YEKST: 5 * 60,
	/** India Standard Time */
	'IST-IN': 5.5 * 60,

	// ! UTC +05:30 to +09:00 (South Asia, Russia, Southeast Asia)
	/** Nepal Time (UTC+05:45) */
	NPT: 5.75 * 60,
	/** Nepal Time (alternative) */
	'NPT-NEPAL': 5.75 * 60,
	/** Bangladesh Time */
	BDT: 6 * 60,
	/** Bangladesh Standard Time */
	'BST-BD': 6 * 60,
	/** Bhutan Time */
	BTT: 6 * 60,
	/** Almaty Time (Kazakhstan) */
	ALMT: 6 * 60,
	/** Omsk Time (Russia) */
	OMST: 6 * 60,
	/** Myanmar Time */
	MMT: 6.5 * 60,
	/** Cocos Islands Time */
	CCT: 6.5 * 60,
	/** Indochina Time (Thailand, Vietnam) */
	ICT: 7 * 60,
	/** Thailand Standard Time */
	THA: 7 * 60,
	/** Krasnoyarsk Time (Russia) */
	KRAT: 7 * 60,
	/** Western Indonesia Time (Jakarta) */
	WIB: 7 * 60,
	/** Hong Kong Time */
	HKT: 8 * 60,
	/** China Standard Time */
	'CST-CHINA': 8 * 60,
	/** Singapore Time */
	SGT: 8 * 60,
	/** Malaysia Time */
	MYT: 8 * 60,
	/** Philippines Time */
	PHT: 8 * 60,
	/** Irkutsk Time (Russia) */
	IRKT: 8 * 60,
	/** Irkutsk Daylight Time (Russia, DST) */
	'IRKT-DST': 9 * 60,
	/** Irkutsk Time (Russia, alternative) */
	'IRKT-RU': 8 * 60,
	/** Australian Western Standard Time */
	AWST: 8 * 60,
	/** Australian Central Western Standard Time (Eucla, UTC+08:45) */
	ACWST: 8.75 * 60,
	/** Western Indonesia Time (Bali) */
	WITA: 8 * 60,
	/** Japan Standard Time */
	JST: 9 * 60,
	/** Korea Standard Time */
	KST: 9 * 60,
	/** Palau Time */
	PWT: 9 * 60,
	/** Yakutsk Time (Russia) */
	YAKT: 9 * 60,
	/** Eastern Indonesia Time (Jayapura) */
	WIT: 9 * 60,

	// ! UTC +09:30 to +14:00 (Australia, Pacific Islands, Russia)
	/** Australian Central Standard Time */
	ACST: 9.5 * 60,
	/** Australian Central Daylight Time (DST) */
	ACDT: 10.5 * 60,
	/** Australian Eastern Standard Time */
	AEST: 10 * 60,
	/** Australian Eastern Daylight Time (DST) */
	AEDT: 11 * 60,
	/** Vladivostok Time (Russia) */
	VLAT: 10 * 60,
	/** Lord Howe Standard Time (UTC+10:30) */
	LHST: 10.5 * 60,
	/** Lord Howe Daylight Time (DST +30min) */
	LHDT: 11 * 60,
	/** Sakhalin Time (Russia) */
	SAKT: 11 * 60,
	/** Magadan Time (Russia) */
	MAGT: 11 * 60,
	/** Norfolk Time (Australia) */
	NFT: 11 * 60,
	/** Chamorro Standard Time (Guam, Northern Mariana Islands) */
	CHST: 10 * 60,
	/** New Zealand Standard Time */
	NZST: 12 * 60,
	/** New Zealand Daylight Time (DST) */
	NZDT: 13 * 60,
	/** Fiji Time */
	FJT: 12 * 60,
	/** Tuvalu Time */
	TVT: 12 * 60,
	/** Chatham Standard Time (New Zealand) */
	CHAST: 12.75 * 60,
	/** Chatham Daylight Time (New Zealand, DST) */
	CHADT: 13.75 * 60,
	/** Chatham Standard Time (alternative) */
	'CHAST-NZ': 12.75 * 60,
	/** Phoenix Island Time (Kiribati) */
	PHOT: 13 * 60,
	/** Tokelau Time */
	TKT: 13 * 60,
	/** Tonga Time */
	TOT: 13 * 60,
	/** New Zealand Antarctica Time */
	NZAT: 13 * 60,
	/** Line Islands Time (Kiribati) */
	LINT: 14 * 60,

	// ! Antarctica (used in research stations)
	/** Rothera Time (Antarctica) */
	ROTT: -3 * 60,
	/** Mawson Time (Antarctica) */
	MAWT: 5 * 60,
	/** Petropavlovsk-Kamchatsky Time (Russia) */
	PETT: 12 * 60,
} as const);

/** List of time-zone labels/names against their corresponding UTC values as object (`{UTCOffset: timeZoneName}`) */
export const TIME_ZONE_LABELS = /* @__PURE__ */ Object.freeze({
	'UTC-12:00': 'Baker Island Time', // and Howland Island
	// 'UTC-11:30': 'Niue Time',
	// 'UTC-11:00': 'Niue Time',
	'UTC-11:00': 'Samoa Standard Time',
	// 'UTC-10:30': 'Marquesas Time',
	'UTC-10:00': 'Hawaii-Aleutian Standard Time',
	'UTC-09:30': 'Marquesas Islands Time',
	'UTC-09:00': 'Alaskan Standard Time',
	// 'UTC-08:30': 'Pitcairn Standard Time',
	'UTC-08:00': 'Pacific Standard Time',
	'UTC-07:30': 'Mountain Standard Time (Unofficial)',
	'UTC-07:00': 'Mountain Standard Time',
	'UTC-06:30': 'Central America Time (Unofficial)',
	'UTC-06:00': 'Central Standard Time',
	// 'UTC-05:30': 'Venezuelan Standard Time (Historical)',
	'UTC-05:00': 'Eastern Standard Time',
	// 'UTC-04:30': 'Venezuelan Standard Time',
	'UTC-04:00': 'Atlantic Standard Time',
	'UTC-03:30': 'Newfoundland Standard Time',
	'UTC-03:00': 'SA Eastern Standard Time',
	'UTC-02:30': 'Mid-Atlantic Time (Unofficial)',
	'UTC-02:00': 'Mid-Atlantic Standard Time',
	'UTC-01:30': 'Azores Time (Unofficial)',
	'UTC-01:00': 'Cape Verde Time',
	'UTC+00:00': 'Greenwich Mean Time',
	'UTC+00:30': 'British Summer Time (Historical)',
	'UTC+01:00': 'Central European Standard Time',
	'UTC+01:30': 'Central Africa Time (Unofficial)',
	'UTC+02:00': 'Eastern European Standard Time',
	'UTC+02:30': 'Israel Standard Time (Historical)',
	'UTC+03:00': 'Arab Standard Time',
	'UTC+03:30': 'Iran Standard Time',
	'UTC+04:00': 'Gulf Standard Time',
	'UTC+04:30': 'Afghanistan Time',
	'UTC+05:00': 'Pakistan Standard Time',
	'UTC+05:30': 'India Standard Time',
	'UTC+05:45': 'Nepal Standard Time',
	'UTC+06:00': 'Bangladesh Standard Time',
	'UTC+06:30': 'Myanmar Standard Time',
	'UTC+07:00': 'Indochina Standard Time',
	'UTC+07:30': 'Western Indonesia Time (Unofficial)',
	'UTC+08:00': 'China Standard Time',
	'UTC+08:30': 'North Korea Standard Time',
	'UTC+08:45': 'South-Western Australia Standard Time',
	'UTC+09:00': 'Japan Standard Time',
	'UTC+09:30': 'Central Australia Standard Time',
	'UTC+10:00': 'Eastern Australia Standard Time',
	'UTC+10:30': 'Lord Howe Standard Time',
	'UTC+11:00': 'Central Pacific Standard Time',
	// 'UTC+11:30': 'Norfolk Island Time',
	'UTC+12:00': 'New Zealand Standard Time',
	'UTC+12:45': 'Chatham Islands Time',
	'UTC+13:00': 'Phoenix Island Time',
	'UTC+13:45': 'Tokelau Time (Unofficial)',
	'UTC+14:00': 'Line Islands Time',
} as Record<UTCOffSet, string>);

export const TIME_ZONE_LIST = /* @__PURE__ */ Object.freeze([
	{
		timeZoneId: 'Africa/Abidjan',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Africa/Accra',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Africa/Addis_Ababa',
		sdtOffset: 'UTC+03:00',
		sdtTzName: 'East Africa Time',
		sdtTzAbr: 'EAT',
	},
	{
		timeZoneId: 'Africa/Algiers',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Africa/Asmara',
		sdtOffset: 'UTC+03:00',
		sdtTzName: 'East Africa Time',
		sdtTzAbr: 'EAT',
	},
	{
		timeZoneId: 'Africa/Asmera',
		sdtOffset: 'UTC+03:00',
		sdtTzName: 'East Africa Time',
		sdtTzAbr: 'EAT',
	},
	{
		timeZoneId: 'Africa/Bamako',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Africa/Bangui',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'West Africa Time',
		sdtTzAbr: 'WAT',
	},
	{
		timeZoneId: 'Africa/Banjul',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Africa/Bissau',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Africa/Blantyre',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Central Africa Time',
		sdtTzAbr: 'CAT',
	},
	{
		timeZoneId: 'Africa/Brazzaville',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'West Africa Time',
		sdtTzAbr: 'WAT',
	},
	{
		timeZoneId: 'Africa/Bujumbura',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Central Africa Time',
		sdtTzAbr: 'CAT',
	},
	{
		timeZoneId: 'Africa/Cairo',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Africa/Casablanca',
		sdtOffset: 'UTC+01:00',
		sdtTzName: '',
		sdtTzAbr: '+01',
	},
	{
		timeZoneId: 'Africa/Ceuta',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Africa/Conakry',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Africa/Dakar',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Africa/Dar_es_Salaam',
		sdtOffset: 'UTC+03:00',
		sdtTzName: 'East Africa Time',
		sdtTzAbr: 'EAT',
	},
	{
		timeZoneId: 'Africa/Djibouti',
		sdtOffset: 'UTC+03:00',
		sdtTzName: 'East Africa Time',
		sdtTzAbr: 'EAT',
	},
	{
		timeZoneId: 'Africa/Douala',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'West Africa Time',
		sdtTzAbr: 'WAT',
	},
	{
		timeZoneId: 'Africa/El_Aaiun',
		sdtOffset: 'UTC+01:00',
		sdtTzName: '',
		sdtTzAbr: '+01',
	},
	{
		timeZoneId: 'Africa/Freetown',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Africa/Gaborone',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Central Africa Time',
		sdtTzAbr: 'CAT',
	},
	{
		timeZoneId: 'Africa/Harare',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Central Africa Time',
		sdtTzAbr: 'CAT',
	},
	{
		timeZoneId: 'Africa/Johannesburg',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'South African Standard Time',
		sdtTzAbr: 'SAST',
	},
	{
		timeZoneId: 'Africa/Juba',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Central Africa Time',
		sdtTzAbr: 'CAT',
	},
	{
		timeZoneId: 'Africa/Kampala',
		sdtOffset: 'UTC+03:00',
		sdtTzName: 'East Africa Time',
		sdtTzAbr: 'EAT',
	},
	{
		timeZoneId: 'Africa/Khartoum',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Central Africa Time',
		sdtTzAbr: 'CAT',
	},
	{
		timeZoneId: 'Africa/Kigali',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Central Africa Time',
		sdtTzAbr: 'CAT',
	},
	{
		timeZoneId: 'Africa/Kinshasa',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'West Africa Time',
		sdtTzAbr: 'WAT',
	},
	{
		timeZoneId: 'Africa/Lagos',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'West Africa Time',
		sdtTzAbr: 'WAT',
	},
	{
		timeZoneId: 'Africa/Libreville',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'West Africa Time',
		sdtTzAbr: 'WAT',
	},
	{
		timeZoneId: 'Africa/Lome',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Africa/Luanda',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'West Africa Time',
		sdtTzAbr: 'WAT',
	},
	{
		timeZoneId: 'Africa/Lubumbashi',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Central Africa Time',
		sdtTzAbr: 'CAT',
	},
	{
		timeZoneId: 'Africa/Lusaka',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Central Africa Time',
		sdtTzAbr: 'CAT',
	},
	{
		timeZoneId: 'Africa/Malabo',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'West Africa Time',
		sdtTzAbr: 'WAT',
	},
	{
		timeZoneId: 'Africa/Maputo',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Central Africa Time',
		sdtTzAbr: 'CAT',
	},
	{
		timeZoneId: 'Africa/Maseru',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'South African Standard Time',
		sdtTzAbr: 'SAST',
	},
	{
		timeZoneId: 'Africa/Mbabane',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'South African Standard Time',
		sdtTzAbr: 'SAST',
	},
	{
		timeZoneId: 'Africa/Mogadishu',
		sdtOffset: 'UTC+03:00',
		sdtTzName: 'East Africa Time',
		sdtTzAbr: 'EAT',
	},
	{
		timeZoneId: 'Africa/Monrovia',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Africa/Nairobi',
		sdtOffset: 'UTC+03:00',
		sdtTzName: 'East Africa Time',
		sdtTzAbr: 'EAT',
	},
	{
		timeZoneId: 'Africa/Ndjamena',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'West Africa Time',
		sdtTzAbr: 'WAT',
	},
	{
		timeZoneId: 'Africa/Niamey',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'West Africa Time',
		sdtTzAbr: 'WAT',
	},
	{
		timeZoneId: 'Africa/Nouakchott',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Africa/Ouagadougou',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Africa/Porto-Novo',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'West Africa Time',
		sdtTzAbr: 'WAT',
	},
	{
		timeZoneId: 'Africa/Sao_Tome',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Africa/Timbuktu',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Africa/Tripoli',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Africa/Tunis',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Africa/Windhoek',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Central Africa Time',
		sdtTzAbr: 'CAT',
	},
	{
		timeZoneId: 'America/Adak',
		sdtOffset: 'UTC−10:00',
		sdtTzName: 'Hawaiian Standard Time',
		sdtTzAbr: 'HST',
	},
	{
		timeZoneId: 'America/Anchorage',
		sdtOffset: 'UTC−09:00',
		sdtTzName: 'Alaskan Standard Time',
		sdtTzAbr: 'AKST',
	},
	{
		timeZoneId: 'America/Anguilla',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Antigua',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Araguaina',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Argentina/Buenos_Aires',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Argentina/Catamarca',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Argentina/ComodRivadavia',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Argentina/Cordoba',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Argentina/Jujuy',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Argentina/La_Rioja',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Argentina/Mendoza',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Argentina/Rio_Gallegos',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Argentina/Salta',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Argentina/San_Juan',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Argentina/San_Luis',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Argentina/Tucuman',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Argentina/Ushuaia',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Aruba',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Asuncion',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Atikokan',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Atka',
		sdtOffset: 'UTC−10:00',
		sdtTzName: 'Hawaiian Standard Time',
		sdtTzAbr: 'HST',
	},
	{
		timeZoneId: 'America/Bahia',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Bahia_Banderas',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Barbados',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Belem',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Belize',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Blanc-Sablon',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Boa_Vista',
		sdtOffset: 'UTC−04:00',
		sdtTzName: '',
		sdtTzAbr: '-04',
	},
	{
		timeZoneId: 'America/Bogota',
		sdtOffset: 'UTC−05:00',
		sdtTzName: '',
		sdtTzAbr: '-05',
	},
	{
		timeZoneId: 'America/Boise',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'America/Buenos_Aires',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Cambridge_Bay',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'America/Campo_Grande',
		sdtOffset: 'UTC−04:00',
		sdtTzName: '',
		sdtTzAbr: '-04',
	},
	{
		timeZoneId: 'America/Cancun',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Caracas',
		sdtOffset: 'UTC−04:00',
		sdtTzName: '',
		sdtTzAbr: '-04',
	},
	{
		timeZoneId: 'America/Catamarca',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Cayenne',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Cayman',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Chicago',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Chihuahua',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Ciudad_Juarez',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'America/Coral_Harbour',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Cordoba',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Costa_Rica',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Coyhaique',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Creston',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'America/Cuiaba',
		sdtOffset: 'UTC−04:00',
		sdtTzName: '',
		sdtTzAbr: '-04',
	},
	{
		timeZoneId: 'America/Curacao',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Danmarkshavn',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'America/Dawson',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'America/Dawson_Creek',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'America/Denver',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'America/Detroit',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Dominica',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Edmonton',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'America/Eirunepe',
		sdtOffset: 'UTC−05:00',
		sdtTzName: '',
		sdtTzAbr: '-05',
	},
	{
		timeZoneId: 'America/El_Salvador',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Ensenada',
		sdtOffset: 'UTC−08:00',
		sdtTzName: 'Pacific Standard Time',
		sdtTzAbr: 'PST',
	},
	{
		timeZoneId: 'America/Fort_Nelson',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'America/Fort_Wayne',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Fortaleza',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Glace_Bay',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Godthab',
		sdtOffset: 'UTC−02:00',
		sdtTzName: '',
		sdtTzAbr: '-02',
	},
	{
		timeZoneId: 'America/Goose_Bay',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Grand_Turk',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Grenada',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Guadeloupe',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Guatemala',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Guayaquil',
		sdtOffset: 'UTC−05:00',
		sdtTzName: '',
		sdtTzAbr: '-05',
	},
	{
		timeZoneId: 'America/Guyana',
		sdtOffset: 'UTC−04:00',
		sdtTzName: '',
		sdtTzAbr: '-04',
	},
	{
		timeZoneId: 'America/Halifax',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Havana',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Cuba Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Hermosillo',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'America/Indiana/Indianapolis',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Indiana/Knox',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Indiana/Marengo',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Indiana/Petersburg',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Indiana/Tell_City',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Indiana/Vevay',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Indiana/Vincennes',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Indiana/Winamac',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Indianapolis',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Inuvik',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'America/Iqaluit',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Jamaica',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Jujuy',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Juneau',
		sdtOffset: 'UTC−09:00',
		sdtTzName: 'Alaskan Standard Time',
		sdtTzAbr: 'AKST',
	},
	{
		timeZoneId: 'America/Kentucky/Louisville',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Kentucky/Monticello',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Knox_IN',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Kralendijk',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/La_Paz',
		sdtOffset: 'UTC−04:00',
		sdtTzName: '',
		sdtTzAbr: '-04',
	},
	{
		timeZoneId: 'America/Lima',
		sdtOffset: 'UTC−05:00',
		sdtTzName: '',
		sdtTzAbr: '-05',
	},
	{
		timeZoneId: 'America/Los_Angeles',
		sdtOffset: 'UTC−08:00',
		sdtTzName: 'Pacific Standard Time',
		sdtTzAbr: 'PST',
	},
	{
		timeZoneId: 'America/Louisville',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Lower_Princes',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Maceio',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Managua',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Manaus',
		sdtOffset: 'UTC−04:00',
		sdtTzName: '',
		sdtTzAbr: '-04',
	},
	{
		timeZoneId: 'America/Marigot',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Martinique',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Matamoros',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Mazatlan',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'America/Mendoza',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Menominee',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Merida',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Metlakatla',
		sdtOffset: 'UTC−09:00',
		sdtTzName: 'Alaskan Standard Time',
		sdtTzAbr: 'AKST',
	},
	{
		timeZoneId: 'America/Mexico_City',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Miquelon',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Moncton',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Monterrey',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Montevideo',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Montreal',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Montserrat',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Nassau',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/New_York',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Nipigon',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Nome',
		sdtOffset: 'UTC−09:00',
		sdtTzName: 'Alaskan Standard Time',
		sdtTzAbr: 'AKST',
	},
	{
		timeZoneId: 'America/Noronha',
		sdtOffset: 'UTC−02:00',
		sdtTzName: '',
		sdtTzAbr: '-02',
	},
	{
		timeZoneId: 'America/North_Dakota/Beulah',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/North_Dakota/Center',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/North_Dakota/New_Salem',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Nuuk',
		sdtOffset: 'UTC−02:00',
		sdtTzName: '',
		sdtTzAbr: '-02',
	},
	{
		timeZoneId: 'America/Ojinaga',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Panama',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Pangnirtung',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Paramaribo',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Phoenix',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'America/Port-au-Prince',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Port_of_Spain',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Porto_Acre',
		sdtOffset: 'UTC−05:00',
		sdtTzName: '',
		sdtTzAbr: '-05',
	},
	{
		timeZoneId: 'America/Porto_Velho',
		sdtOffset: 'UTC−04:00',
		sdtTzName: '',
		sdtTzAbr: '-04',
	},
	{
		timeZoneId: 'America/Puerto_Rico',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Punta_Arenas',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Rainy_River',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Rankin_Inlet',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Recife',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Regina',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Resolute',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Rio_Branco',
		sdtOffset: 'UTC−05:00',
		sdtTzName: '',
		sdtTzAbr: '-05',
	},
	{
		timeZoneId: 'America/Rosario',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Santa_Isabel',
		sdtOffset: 'UTC−08:00',
		sdtTzName: 'Pacific Standard Time',
		sdtTzAbr: 'PST',
	},
	{
		timeZoneId: 'America/Santarem',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Santiago',
		sdtOffset: 'UTC−04:00',
		sdtTzName: '',
		sdtTzAbr: '-04',
	},
	{
		timeZoneId: 'America/Santo_Domingo',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Sao_Paulo',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'America/Scoresbysund',
		sdtOffset: 'UTC−02:00',
		sdtTzName: '',
		sdtTzAbr: '-02',
	},
	{
		timeZoneId: 'America/Shiprock',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'America/Sitka',
		sdtOffset: 'UTC−09:00',
		sdtTzName: 'Alaskan Standard Time',
		sdtTzAbr: 'AKST',
	},
	{
		timeZoneId: 'America/St_Barthelemy',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/St_Johns',
		sdtOffset: 'UTC−03:30',
		sdtTzName: 'Newfoundland Standard Time',
		sdtTzAbr: 'NST',
	},
	{
		timeZoneId: 'America/St_Kitts',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/St_Lucia',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/St_Thomas',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/St_Vincent',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Swift_Current',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Tegucigalpa',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Thule',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Thunder_Bay',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Tijuana',
		sdtOffset: 'UTC−08:00',
		sdtTzName: 'Pacific Standard Time',
		sdtTzAbr: 'PST',
	},
	{
		timeZoneId: 'America/Toronto',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'America/Tortola',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Vancouver',
		sdtOffset: 'UTC−08:00',
		sdtTzName: 'Pacific Standard Time',
		sdtTzAbr: 'PST',
	},
	{
		timeZoneId: 'America/Virgin',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'America/Whitehorse',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'America/Winnipeg',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'America/Yakutat',
		sdtOffset: 'UTC−09:00',
		sdtTzName: 'Alaskan Standard Time',
		sdtTzAbr: 'AKST',
	},
	{
		timeZoneId: 'America/Yellowknife',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'Antarctica/Casey',
		sdtOffset: 'UTC+08:00',
		sdtTzName: '',
		sdtTzAbr: '+08',
	},
	{
		timeZoneId: 'Antarctica/Davis',
		sdtOffset: 'UTC+07:00',
		sdtTzName: '',
		sdtTzAbr: '+07',
	},
	{
		timeZoneId: 'Antarctica/DumontDUrville',
		sdtOffset: 'UTC+10:00',
		sdtTzName: '',
		sdtTzAbr: '+10',
	},
	{
		timeZoneId: 'Antarctica/Macquarie',
		sdtOffset: 'UTC+10:00',
		sdtTzName: 'Australian Eastern Standard Time',
		sdtTzAbr: 'AEST',
	},
	{
		timeZoneId: 'Antarctica/Mawson',
		sdtOffset: 'UTC+05:00',
		sdtTzName: '',
		sdtTzAbr: '+05',
	},
	{
		timeZoneId: 'Antarctica/McMurdo',
		sdtOffset: 'UTC+12:00',
		sdtTzName: 'New Zealand Standard Time',
		sdtTzAbr: 'NZST',
	},
	{
		timeZoneId: 'Antarctica/Palmer',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'Antarctica/Rothera',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'Antarctica/South_Pole',
		sdtOffset: 'UTC+12:00',
		sdtTzName: 'New Zealand Standard Time',
		sdtTzAbr: 'NZST',
	},
	{
		timeZoneId: 'Antarctica/Syowa',
		sdtOffset: 'UTC+03:00',
		sdtTzName: '',
		sdtTzAbr: '+03',
	},
	{
		timeZoneId: 'Antarctica/Troll',
		sdtOffset: 'UTC+00:00',
		sdtTzName: '',
		sdtTzAbr: '+00',
	},
	{
		timeZoneId: 'Antarctica/Vostok',
		sdtOffset: 'UTC+05:00',
		sdtTzName: '',
		sdtTzAbr: '+05',
	},
	{
		timeZoneId: 'Arctic/Longyearbyen',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Asia/Aden',
		sdtOffset: 'UTC+03:00',
		sdtTzName: '',
		sdtTzAbr: '+03',
	},
	{
		timeZoneId: 'Asia/Almaty',
		sdtOffset: 'UTC+05:00',
		sdtTzName: '',
		sdtTzAbr: '+05',
	},
	{
		timeZoneId: 'Asia/Amman',
		sdtOffset: 'UTC+03:00',
		sdtTzName: '',
		sdtTzAbr: '+03',
	},
	{
		timeZoneId: 'Asia/Anadyr',
		sdtOffset: 'UTC+12:00',
		sdtTzName: '',
		sdtTzAbr: '+12',
	},
	{
		timeZoneId: 'Asia/Aqtau',
		sdtOffset: 'UTC+05:00',
		sdtTzName: '',
		sdtTzAbr: '+05',
	},
	{
		timeZoneId: 'Asia/Aqtobe',
		sdtOffset: 'UTC+05:00',
		sdtTzName: '',
		sdtTzAbr: '+05',
	},
	{
		timeZoneId: 'Asia/Ashgabat',
		sdtOffset: 'UTC+05:00',
		sdtTzName: '',
		sdtTzAbr: '+05',
	},
	{
		timeZoneId: 'Asia/Ashkhabad',
		sdtOffset: 'UTC+05:00',
		sdtTzName: '',
		sdtTzAbr: '+05',
	},
	{
		timeZoneId: 'Asia/Atyrau',
		sdtOffset: 'UTC+05:00',
		sdtTzName: '',
		sdtTzAbr: '+05',
	},
	{
		timeZoneId: 'Asia/Baghdad',
		sdtOffset: 'UTC+03:00',
		sdtTzName: '',
		sdtTzAbr: '+03',
	},
	{
		timeZoneId: 'Asia/Bahrain',
		sdtOffset: 'UTC+03:00',
		sdtTzName: '',
		sdtTzAbr: '+03',
	},
	{
		timeZoneId: 'Asia/Baku',
		sdtOffset: 'UTC+04:00',
		sdtTzName: '',
		sdtTzAbr: '+04',
	},
	{
		timeZoneId: 'Asia/Bangkok',
		sdtOffset: 'UTC+07:00',
		sdtTzName: '',
		sdtTzAbr: '+07',
	},
	{
		timeZoneId: 'Asia/Barnaul',
		sdtOffset: 'UTC+07:00',
		sdtTzName: '',
		sdtTzAbr: '+07',
	},
	{
		timeZoneId: 'Asia/Beirut',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Asia/Bishkek',
		sdtOffset: 'UTC+06:00',
		sdtTzName: '',
		sdtTzAbr: '+06',
	},
	{
		timeZoneId: 'Asia/Brunei',
		sdtOffset: 'UTC+08:00',
		sdtTzName: '',
		sdtTzAbr: '+08',
	},
	{
		timeZoneId: 'Asia/Calcutta',
		sdtOffset: 'UTC+05:30',
		sdtTzName: 'Indian Standard Time',
		sdtTzAbr: 'IST',
	},
	{
		timeZoneId: 'Asia/Chita',
		sdtOffset: 'UTC+09:00',
		sdtTzName: '',
		sdtTzAbr: '+09',
	},
	{
		timeZoneId: 'Asia/Choibalsan',
		sdtOffset: 'UTC+08:00',
		sdtTzName: '',
		sdtTzAbr: '+08',
	},
	{
		timeZoneId: 'Asia/Chongqing',
		sdtOffset: 'UTC+08:00',
		sdtTzName: 'China Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'Asia/Chungking',
		sdtOffset: 'UTC+08:00',
		sdtTzName: 'China Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'Asia/Colombo',
		sdtOffset: 'UTC+05:30',
		sdtTzName: '',
		sdtTzAbr: '+0530',
	},
	{
		timeZoneId: 'Asia/Dacca',
		sdtOffset: 'UTC+06:00',
		sdtTzName: '',
		sdtTzAbr: '+06',
	},
	{
		timeZoneId: 'Asia/Damascus',
		sdtOffset: 'UTC+03:00',
		sdtTzName: '',
		sdtTzAbr: '+03',
	},
	{
		timeZoneId: 'Asia/Dhaka',
		sdtOffset: 'UTC+06:00',
		sdtTzName: '',
		sdtTzAbr: '+06',
	},
	{
		timeZoneId: 'Asia/Dili',
		sdtOffset: 'UTC+09:00',
		sdtTzName: '',
		sdtTzAbr: '+09',
	},
	{
		timeZoneId: 'Asia/Dubai',
		sdtOffset: 'UTC+04:00',
		sdtTzName: '',
		sdtTzAbr: '+04',
	},
	{
		timeZoneId: 'Asia/Dushanbe',
		sdtOffset: 'UTC+05:00',
		sdtTzName: '',
		sdtTzAbr: '+05',
	},
	{
		timeZoneId: 'Asia/Famagusta',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Asia/Gaza',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Asia/Harbin',
		sdtOffset: 'UTC+08:00',
		sdtTzName: 'China Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'Asia/Hebron',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Asia/Ho_Chi_Minh',
		sdtOffset: 'UTC+07:00',
		sdtTzName: '',
		sdtTzAbr: '+07',
	},
	{
		timeZoneId: 'Asia/Hong_Kong',
		sdtOffset: 'UTC+08:00',
		sdtTzName: 'Hong Kong Time',
		sdtTzAbr: 'HKT',
	},
	{
		timeZoneId: 'Asia/Hovd',
		sdtOffset: 'UTC+07:00',
		sdtTzName: '',
		sdtTzAbr: '+07',
	},
	{
		timeZoneId: 'Asia/Irkutsk',
		sdtOffset: 'UTC+08:00',
		sdtTzName: '',
		sdtTzAbr: '+08',
	},
	{
		timeZoneId: 'Asia/Istanbul',
		sdtOffset: 'UTC+03:00',
		sdtTzName: '',
		sdtTzAbr: '+03',
	},
	{
		timeZoneId: 'Asia/Jakarta',
		sdtOffset: 'UTC+07:00',
		sdtTzName: 'Western Indonesia Time',
		sdtTzAbr: 'WIB',
	},
	{
		timeZoneId: 'Asia/Jayapura',
		sdtOffset: 'UTC+09:00',
		sdtTzName: 'Eastern Indonesia Time',
		sdtTzAbr: 'WIT',
	},
	{
		timeZoneId: 'Asia/Jerusalem',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Israel Standard Time',
		sdtTzAbr: 'IST',
	},
	{
		timeZoneId: 'Asia/Kabul',
		sdtOffset: 'UTC+04:30',
		sdtTzName: '',
		sdtTzAbr: '+0430',
	},
	{
		timeZoneId: 'Asia/Kamchatka',
		sdtOffset: 'UTC+12:00',
		sdtTzName: '',
		sdtTzAbr: '+12',
	},
	{
		timeZoneId: 'Asia/Karachi',
		sdtOffset: 'UTC+05:00',
		sdtTzName: 'Pakistan Standard Time',
		sdtTzAbr: 'PKT',
	},
	{
		timeZoneId: 'Asia/Kashgar',
		sdtOffset: 'UTC+06:00',
		sdtTzName: '',
		sdtTzAbr: '+06',
	},
	{
		timeZoneId: 'Asia/Kathmandu',
		sdtOffset: 'UTC+05:45',
		sdtTzName: '',
		sdtTzAbr: '+0545',
	},
	{
		timeZoneId: 'Asia/Katmandu',
		sdtOffset: 'UTC+05:45',
		sdtTzName: '',
		sdtTzAbr: '+0545',
	},
	{
		timeZoneId: 'Asia/Khandyga',
		sdtOffset: 'UTC+09:00',
		sdtTzName: '',
		sdtTzAbr: '+09',
	},
	{
		timeZoneId: 'Asia/Kolkata',
		sdtOffset: 'UTC+05:30',
		sdtTzName: 'Indian Standard Time',
		sdtTzAbr: 'IST',
	},
	{
		timeZoneId: 'Asia/Krasnoyarsk',
		sdtOffset: 'UTC+07:00',
		sdtTzName: '',
		sdtTzAbr: '+07',
	},
	{
		timeZoneId: 'Asia/Kuala_Lumpur',
		sdtOffset: 'UTC+08:00',
		sdtTzName: '',
		sdtTzAbr: '+08',
	},
	{
		timeZoneId: 'Asia/Kuching',
		sdtOffset: 'UTC+08:00',
		sdtTzName: '',
		sdtTzAbr: '+08',
	},
	{
		timeZoneId: 'Asia/Kuwait',
		sdtOffset: 'UTC+03:00',
		sdtTzName: '',
		sdtTzAbr: '+03',
	},
	{
		timeZoneId: 'Asia/Macao',
		sdtOffset: 'UTC+08:00',
		sdtTzName: 'China Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'Asia/Macau',
		sdtOffset: 'UTC+08:00',
		sdtTzName: 'China Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'Asia/Magadan',
		sdtOffset: 'UTC+11:00',
		sdtTzName: '',
		sdtTzAbr: '+11',
	},
	{
		timeZoneId: 'Asia/Makassar',
		sdtOffset: 'UTC+08:00',
		sdtTzName: 'Central Indonesia Time',
		sdtTzAbr: 'WITA',
	},
	{
		timeZoneId: 'Asia/Manila',
		sdtOffset: 'UTC+08:00',
		sdtTzName: 'Philippine Standard Time',
		sdtTzAbr: 'PST',
	},
	{
		timeZoneId: 'Asia/Muscat',
		sdtOffset: 'UTC+04:00',
		sdtTzName: '',
		sdtTzAbr: '+04',
	},
	{
		timeZoneId: 'Asia/Nicosia',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Asia/Novokuznetsk',
		sdtOffset: 'UTC+07:00',
		sdtTzName: '',
		sdtTzAbr: '+07',
	},
	{
		timeZoneId: 'Asia/Novosibirsk',
		sdtOffset: 'UTC+07:00',
		sdtTzName: '',
		sdtTzAbr: '+07',
	},
	{
		timeZoneId: 'Asia/Omsk',
		sdtOffset: 'UTC+06:00',
		sdtTzName: '',
		sdtTzAbr: '+06',
	},
	{
		timeZoneId: 'Asia/Oral',
		sdtOffset: 'UTC+05:00',
		sdtTzName: '',
		sdtTzAbr: '+05',
	},
	{
		timeZoneId: 'Asia/Phnom_Penh',
		sdtOffset: 'UTC+07:00',
		sdtTzName: '',
		sdtTzAbr: '+07',
	},
	{
		timeZoneId: 'Asia/Pontianak',
		sdtOffset: 'UTC+07:00',
		sdtTzName: 'Western Indonesia Time',
		sdtTzAbr: 'WIB',
	},
	{
		timeZoneId: 'Asia/Pyongyang',
		sdtOffset: 'UTC+09:00',
		sdtTzName: 'Korean Standard Time',
		sdtTzAbr: 'KST',
	},
	{
		timeZoneId: 'Asia/Qatar',
		sdtOffset: 'UTC+03:00',
		sdtTzName: '',
		sdtTzAbr: '+03',
	},
	{
		timeZoneId: 'Asia/Qostanay',
		sdtOffset: 'UTC+05:00',
		sdtTzName: '',
		sdtTzAbr: '+05',
	},
	{
		timeZoneId: 'Asia/Qyzylorda',
		sdtOffset: 'UTC+05:00',
		sdtTzName: '',
		sdtTzAbr: '+05',
	},
	{
		timeZoneId: 'Asia/Rangoon',
		sdtOffset: 'UTC+06:30',
		sdtTzName: '',
		sdtTzAbr: '+0630',
	},
	{
		timeZoneId: 'Asia/Riyadh',
		sdtOffset: 'UTC+03:00',
		sdtTzName: '',
		sdtTzAbr: '+03',
	},
	{
		timeZoneId: 'Asia/Saigon',
		sdtOffset: 'UTC+07:00',
		sdtTzName: '',
		sdtTzAbr: '+07',
	},
	{
		timeZoneId: 'Asia/Sakhalin',
		sdtOffset: 'UTC+11:00',
		sdtTzName: '',
		sdtTzAbr: '+11',
	},
	{
		timeZoneId: 'Asia/Samarkand',
		sdtOffset: 'UTC+05:00',
		sdtTzName: '',
		sdtTzAbr: '+05',
	},
	{
		timeZoneId: 'Asia/Seoul',
		sdtOffset: 'UTC+09:00',
		sdtTzName: 'Korean Standard Time',
		sdtTzAbr: 'KST',
	},
	{
		timeZoneId: 'Asia/Shanghai',
		sdtOffset: 'UTC+08:00',
		sdtTzName: 'China Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'Asia/Singapore',
		sdtOffset: 'UTC+08:00',
		sdtTzName: '',
		sdtTzAbr: '+08',
	},
	{
		timeZoneId: 'Asia/Srednekolymsk',
		sdtOffset: 'UTC+11:00',
		sdtTzName: '',
		sdtTzAbr: '+11',
	},
	{
		timeZoneId: 'Asia/Taipei',
		sdtOffset: 'UTC+08:00',
		sdtTzName: 'China Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'Asia/Tashkent',
		sdtOffset: 'UTC+05:00',
		sdtTzName: '',
		sdtTzAbr: '+05',
	},
	{
		timeZoneId: 'Asia/Tbilisi',
		sdtOffset: 'UTC+04:00',
		sdtTzName: '',
		sdtTzAbr: '+04',
	},
	{
		timeZoneId: 'Asia/Tehran',
		sdtOffset: 'UTC+03:30',
		sdtTzName: '',
		sdtTzAbr: '+0330',
	},
	{
		timeZoneId: 'Asia/Tel_Aviv',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Israel Standard Time',
		sdtTzAbr: 'IST',
	},
	{
		timeZoneId: 'Asia/Thimbu',
		sdtOffset: 'UTC+06:00',
		sdtTzName: '',
		sdtTzAbr: '+06',
	},
	{
		timeZoneId: 'Asia/Thimphu',
		sdtOffset: 'UTC+06:00',
		sdtTzName: '',
		sdtTzAbr: '+06',
	},
	{
		timeZoneId: 'Asia/Tokyo',
		sdtOffset: 'UTC+09:00',
		sdtTzName: 'Japanese Standard Time',
		sdtTzAbr: 'JST',
	},
	{
		timeZoneId: 'Asia/Tomsk',
		sdtOffset: 'UTC+07:00',
		sdtTzName: '',
		sdtTzAbr: '+07',
	},
	{
		timeZoneId: 'Asia/Ujung_Pandang',
		sdtOffset: 'UTC+08:00',
		sdtTzName: 'Central Indonesia Time',
		sdtTzAbr: 'WITA',
	},
	{
		timeZoneId: 'Asia/Ulaanbaatar',
		sdtOffset: 'UTC+08:00',
		sdtTzName: '',
		sdtTzAbr: '+08',
	},
	{
		timeZoneId: 'Asia/Ulan_Bator',
		sdtOffset: 'UTC+08:00',
		sdtTzName: '',
		sdtTzAbr: '+08',
	},
	{
		timeZoneId: 'Asia/Urumqi',
		sdtOffset: 'UTC+06:00',
		sdtTzName: '',
		sdtTzAbr: '+06',
	},
	{
		timeZoneId: 'Asia/Ust-Nera',
		sdtOffset: 'UTC+10:00',
		sdtTzName: '',
		sdtTzAbr: '+10',
	},
	{
		timeZoneId: 'Asia/Vientiane',
		sdtOffset: 'UTC+07:00',
		sdtTzName: '',
		sdtTzAbr: '+07',
	},
	{
		timeZoneId: 'Asia/Vladivostok',
		sdtOffset: 'UTC+10:00',
		sdtTzName: '',
		sdtTzAbr: '+10',
	},
	{
		timeZoneId: 'Asia/Yakutsk',
		sdtOffset: 'UTC+09:00',
		sdtTzName: '',
		sdtTzAbr: '+09',
	},
	{
		timeZoneId: 'Asia/Yangon',
		sdtOffset: 'UTC+06:30',
		sdtTzName: '',
		sdtTzAbr: '+0630',
	},
	{
		timeZoneId: 'Asia/Yekaterinburg',
		sdtOffset: 'UTC+05:00',
		sdtTzName: '',
		sdtTzAbr: '+05',
	},
	{
		timeZoneId: 'Asia/Yerevan',
		sdtOffset: 'UTC+04:00',
		sdtTzName: '',
		sdtTzAbr: '+04',
	},
	{
		timeZoneId: 'Atlantic/Azores',
		sdtOffset: 'UTC−01:00',
		sdtTzName: '',
		sdtTzAbr: '-01',
	},
	{
		timeZoneId: 'Atlantic/Bermuda',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'Atlantic/Canary',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Western European Time',
		sdtTzAbr: 'WET',
	},
	{
		timeZoneId: 'Atlantic/Cape_Verde',
		sdtOffset: 'UTC−01:00',
		sdtTzName: '',
		sdtTzAbr: '-01',
	},
	{
		timeZoneId: 'Atlantic/Faeroe',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Western European Time',
		sdtTzAbr: 'WET',
	},
	{
		timeZoneId: 'Atlantic/Faroe',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Western European Time',
		sdtTzAbr: 'WET',
	},
	{
		timeZoneId: 'Atlantic/Jan_Mayen',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Atlantic/Madeira',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Western European Time',
		sdtTzAbr: 'WET',
	},
	{
		timeZoneId: 'Atlantic/Reykjavik',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Atlantic/South_Georgia',
		sdtOffset: 'UTC−02:00',
		sdtTzName: '',
		sdtTzAbr: '-02',
	},
	{
		timeZoneId: 'Atlantic/St_Helena',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Atlantic/Stanley',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'Australia/ACT',
		sdtOffset: 'UTC+10:00',
		sdtTzName: 'Australian Eastern Standard Time',
		sdtTzAbr: 'AEST',
	},
	{
		timeZoneId: 'Australia/Adelaide',
		sdtOffset: 'UTC+09:30',
		sdtTzName: 'Australian Central Standard Time',
		sdtTzAbr: 'ACST',
	},
	{
		timeZoneId: 'Australia/Brisbane',
		sdtOffset: 'UTC+10:00',
		sdtTzName: 'Australian Eastern Standard Time',
		sdtTzAbr: 'AEST',
	},
	{
		timeZoneId: 'Australia/Broken_Hill',
		sdtOffset: 'UTC+09:30',
		sdtTzName: 'Australian Central Standard Time',
		sdtTzAbr: 'ACST',
	},
	{
		timeZoneId: 'Australia/Canberra',
		sdtOffset: 'UTC+10:00',
		sdtTzName: 'Australian Eastern Standard Time',
		sdtTzAbr: 'AEST',
	},
	{
		timeZoneId: 'Australia/Currie',
		sdtOffset: 'UTC+10:00',
		sdtTzName: 'Australian Eastern Standard Time',
		sdtTzAbr: 'AEST',
	},
	{
		timeZoneId: 'Australia/Darwin',
		sdtOffset: 'UTC+09:30',
		sdtTzName: 'Australian Central Standard Time',
		sdtTzAbr: 'ACST',
	},
	{
		timeZoneId: 'Australia/Eucla',
		sdtOffset: 'UTC+08:45',
		sdtTzName: '',
		sdtTzAbr: '+0845',
	},
	{
		timeZoneId: 'Australia/Hobart',
		sdtOffset: 'UTC+10:00',
		sdtTzName: 'Australian Eastern Standard Time',
		sdtTzAbr: 'AEST',
	},
	{
		timeZoneId: 'Australia/LHI',
		sdtOffset: 'UTC+10:30',
		sdtTzName: '',
		sdtTzAbr: '+1030',
	},
	{
		timeZoneId: 'Australia/Lindeman',
		sdtOffset: 'UTC+10:00',
		sdtTzName: 'Australian Eastern Standard Time',
		sdtTzAbr: 'AEST',
	},
	{
		timeZoneId: 'Australia/Lord_Howe',
		sdtOffset: 'UTC+10:30',
		sdtTzName: '',
		sdtTzAbr: '+1030',
	},
	{
		timeZoneId: 'Australia/Melbourne',
		sdtOffset: 'UTC+10:00',
		sdtTzName: 'Australian Eastern Standard Time',
		sdtTzAbr: 'AEST',
	},
	{
		timeZoneId: 'Australia/North',
		sdtOffset: 'UTC+09:30',
		sdtTzName: 'Australian Central Standard Time',
		sdtTzAbr: 'ACST',
	},
	{
		timeZoneId: 'Australia/NSW',
		sdtOffset: 'UTC+10:00',
		sdtTzName: 'Australian Eastern Standard Time',
		sdtTzAbr: 'AEST',
	},
	{
		timeZoneId: 'Australia/Perth',
		sdtOffset: 'UTC+08:00',
		sdtTzName: 'Australian Western Standard Time',
		sdtTzAbr: 'AWST',
	},
	{
		timeZoneId: 'Australia/Queensland',
		sdtOffset: 'UTC+10:00',
		sdtTzName: 'Australian Eastern Standard Time',
		sdtTzAbr: 'AEST',
	},
	{
		timeZoneId: 'Australia/South',
		sdtOffset: 'UTC+09:30',
		sdtTzName: 'Australian Central Standard Time',
		sdtTzAbr: 'ACST',
	},
	{
		timeZoneId: 'Australia/Sydney',
		sdtOffset: 'UTC+10:00',
		sdtTzName: 'Australian Eastern Standard Time',
		sdtTzAbr: 'AEST',
	},
	{
		timeZoneId: 'Australia/Tasmania',
		sdtOffset: 'UTC+10:00',
		sdtTzName: 'Australian Eastern Standard Time',
		sdtTzAbr: 'AEST',
	},
	{
		timeZoneId: 'Australia/Victoria',
		sdtOffset: 'UTC+10:00',
		sdtTzName: 'Australian Eastern Standard Time',
		sdtTzAbr: 'AEST',
	},
	{
		timeZoneId: 'Australia/West',
		sdtOffset: 'UTC+08:00',
		sdtTzName: 'Australian Western Standard Time',
		sdtTzAbr: 'AWST',
	},
	{
		timeZoneId: 'Australia/Yancowinna',
		sdtOffset: 'UTC+09:30',
		sdtTzName: 'Australian Central Standard Time',
		sdtTzAbr: 'ACST',
	},
	{
		timeZoneId: 'Brazil/Acre',
		sdtOffset: 'UTC−05:00',
		sdtTzName: '',
		sdtTzAbr: '-05',
	},
	{
		timeZoneId: 'Brazil/DeNoronha',
		sdtOffset: 'UTC−02:00',
		sdtTzName: '',
		sdtTzAbr: '-02',
	},
	{
		timeZoneId: 'Brazil/East',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'Brazil/West',
		sdtOffset: 'UTC−04:00',
		sdtTzName: '',
		sdtTzAbr: '-04',
	},
	{
		timeZoneId: 'Canada/Atlantic',
		sdtOffset: 'UTC−04:00',
		sdtTzName: 'Atlantic Standard Time',
		sdtTzAbr: 'AST',
	},
	{
		timeZoneId: 'Canada/Central',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'Canada/Eastern',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'Canada/Mountain',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'Canada/Newfoundland',
		sdtOffset: 'UTC−03:30',
		sdtTzName: 'Newfoundland Standard Time',
		sdtTzAbr: 'NST',
	},
	{
		timeZoneId: 'Canada/Pacific',
		sdtOffset: 'UTC−08:00',
		sdtTzName: 'Pacific Standard Time',
		sdtTzAbr: 'PST',
	},
	{
		timeZoneId: 'Canada/Saskatchewan',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'Canada/Yukon',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'CET',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Chile/Continental',
		sdtOffset: 'UTC−04:00',
		sdtTzName: '',
		sdtTzAbr: '',
	},
	{
		timeZoneId: 'Chile/EasterIsland',
		sdtOffset: 'UTC−06:00',
		sdtTzName: '',
		sdtTzAbr: '',
	},
	{
		timeZoneId: 'CST6CDT',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'Cuba',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Cuba Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'EET',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Egypt',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Eire',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'EST',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'EST5EDT',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'Etc/GMT',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Etc/GMT+0',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Etc/GMT+1',
		sdtOffset: 'UTC−01:00',
		sdtTzName: '',
		sdtTzAbr: '-01',
	},
	{
		timeZoneId: 'Etc/GMT+10',
		sdtOffset: 'UTC−10:00',
		sdtTzName: '',
		sdtTzAbr: '-10',
	},
	{
		timeZoneId: 'Etc/GMT+11',
		sdtOffset: 'UTC−11:00',
		sdtTzName: '',
		sdtTzAbr: '-11',
	},
	{
		timeZoneId: 'Etc/GMT+12',
		sdtOffset: 'UTC−12:00',
		sdtTzName: '',
		sdtTzAbr: '-12',
	},
	{
		timeZoneId: 'Etc/GMT+2',
		sdtOffset: 'UTC−02:00',
		sdtTzName: '',
		sdtTzAbr: '-02',
	},
	{
		timeZoneId: 'Etc/GMT+3',
		sdtOffset: 'UTC−03:00',
		sdtTzName: '',
		sdtTzAbr: '-03',
	},
	{
		timeZoneId: 'Etc/GMT+4',
		sdtOffset: 'UTC−04:00',
		sdtTzName: '',
		sdtTzAbr: '-04',
	},
	{
		timeZoneId: 'Etc/GMT+5',
		sdtOffset: 'UTC−05:00',
		sdtTzName: '',
		sdtTzAbr: '-05',
	},
	{
		timeZoneId: 'Etc/GMT+6',
		sdtOffset: 'UTC−06:00',
		sdtTzName: '',
		sdtTzAbr: '-06',
	},
	{
		timeZoneId: 'Etc/GMT+7',
		sdtOffset: 'UTC−07:00',
		sdtTzName: '',
		sdtTzAbr: '-07',
	},
	{
		timeZoneId: 'Etc/GMT+8',
		sdtOffset: 'UTC−08:00',
		sdtTzName: '',
		sdtTzAbr: '-08',
	},
	{
		timeZoneId: 'Etc/GMT+9',
		sdtOffset: 'UTC−09:00',
		sdtTzName: '',
		sdtTzAbr: '-09',
	},
	{
		timeZoneId: 'Etc/GMT-0',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Etc/GMT-1',
		sdtOffset: 'UTC+01:00',
		sdtTzName: '',
		sdtTzAbr: '+01',
	},
	{
		timeZoneId: 'Etc/GMT-10',
		sdtOffset: 'UTC+10:00',
		sdtTzName: '',
		sdtTzAbr: '+10',
	},
	{
		timeZoneId: 'Etc/GMT-11',
		sdtOffset: 'UTC+11:00',
		sdtTzName: '',
		sdtTzAbr: '+11',
	},
	{
		timeZoneId: 'Etc/GMT-12',
		sdtOffset: 'UTC+12:00',
		sdtTzName: '',
		sdtTzAbr: '+12',
	},
	{
		timeZoneId: 'Etc/GMT-13',
		sdtOffset: 'UTC+13:00',
		sdtTzName: '',
		sdtTzAbr: '+13',
	},
	{
		timeZoneId: 'Etc/GMT-14',
		sdtOffset: 'UTC+14:00',
		sdtTzName: '',
		sdtTzAbr: '+14',
	},
	{
		timeZoneId: 'Etc/GMT-2',
		sdtOffset: 'UTC+02:00',
		sdtTzName: '',
		sdtTzAbr: '+02',
	},
	{
		timeZoneId: 'Etc/GMT-3',
		sdtOffset: 'UTC+03:00',
		sdtTzName: '',
		sdtTzAbr: '+03',
	},
	{
		timeZoneId: 'Etc/GMT-4',
		sdtOffset: 'UTC+04:00',
		sdtTzName: '',
		sdtTzAbr: '+04',
	},
	{
		timeZoneId: 'Etc/GMT-5',
		sdtOffset: 'UTC+05:00',
		sdtTzName: '',
		sdtTzAbr: '+05',
	},
	{
		timeZoneId: 'Etc/GMT-6',
		sdtOffset: 'UTC+06:00',
		sdtTzName: '',
		sdtTzAbr: '+06',
	},
	{
		timeZoneId: 'Etc/GMT-7',
		sdtOffset: 'UTC+07:00',
		sdtTzName: '',
		sdtTzAbr: '+07',
	},
	{
		timeZoneId: 'Etc/GMT-8',
		sdtOffset: 'UTC+08:00',
		sdtTzName: '',
		sdtTzAbr: '+08',
	},
	{
		timeZoneId: 'Etc/GMT-9',
		sdtOffset: 'UTC+09:00',
		sdtTzName: '',
		sdtTzAbr: '+09',
	},
	{
		timeZoneId: 'Etc/GMT0',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Etc/Greenwich',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Etc/UCT',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Coordinated Universal Time',
		sdtTzAbr: 'UTC',
	},
	{
		timeZoneId: 'Etc/Universal',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Coordinated Universal Time',
		sdtTzAbr: 'UTC',
	},
	{
		timeZoneId: 'Etc/UTC',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Coordinated Universal Time',
		sdtTzAbr: 'UTC',
	},
	{
		timeZoneId: 'Etc/Zulu',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Coordinated Universal Time',
		sdtTzAbr: 'UTC',
	},
	{
		timeZoneId: 'Europe/Amsterdam',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Andorra',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Astrakhan',
		sdtOffset: 'UTC+04:00',
		sdtTzName: '',
		sdtTzAbr: '+04',
	},
	{
		timeZoneId: 'Europe/Athens',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Europe/Belfast',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Europe/Belgrade',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Berlin',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Bratislava',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Brussels',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Bucharest',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Europe/Budapest',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Busingen',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Chisinau',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Europe/Copenhagen',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Dublin',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Europe/Gibraltar',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Guernsey',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Europe/Helsinki',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Europe/Isle_of_Man',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Europe/Istanbul',
		sdtOffset: 'UTC+03:00',
		sdtTzName: '',
		sdtTzAbr: '+03',
	},
	{
		timeZoneId: 'Europe/Jersey',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Europe/Kaliningrad',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Europe/Kiev',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Europe/Kirov',
		sdtOffset: 'UTC+03:00',
		sdtTzName: 'Moscow Time',
		sdtTzAbr: 'MSK',
	},
	{
		timeZoneId: 'Europe/Kyiv',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Europe/Lisbon',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Western European Time',
		sdtTzAbr: 'WET',
	},
	{
		timeZoneId: 'Europe/Ljubljana',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/London',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Europe/Luxembourg',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Madrid',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Malta',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Mariehamn',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Europe/Minsk',
		sdtOffset: 'UTC+03:00',
		sdtTzName: '',
		sdtTzAbr: '+03',
	},
	{
		timeZoneId: 'Europe/Monaco',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Moscow',
		sdtOffset: 'UTC+03:00',
		sdtTzName: 'Moscow Time',
		sdtTzAbr: 'MSK',
	},
	{
		timeZoneId: 'Europe/Nicosia',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Europe/Oslo',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Paris',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Podgorica',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Prague',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Riga',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Europe/Rome',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Samara',
		sdtOffset: 'UTC+04:00',
		sdtTzName: '',
		sdtTzAbr: '+04',
	},
	{
		timeZoneId: 'Europe/San_Marino',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Sarajevo',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Saratov',
		sdtOffset: 'UTC+04:00',
		sdtTzName: '',
		sdtTzAbr: '+04',
	},
	{
		timeZoneId: 'Europe/Simferopol',
		sdtOffset: 'UTC+03:00',
		sdtTzName: 'Moscow Time',
		sdtTzAbr: 'MSK',
	},
	{
		timeZoneId: 'Europe/Skopje',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Sofia',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Europe/Stockholm',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Tallinn',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Europe/Tirane',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Tiraspol',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Europe/Ulyanovsk',
		sdtOffset: 'UTC+04:00',
		sdtTzName: '',
		sdtTzAbr: '+04',
	},
	{
		timeZoneId: 'Europe/Uzhgorod',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Europe/Vaduz',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Vatican',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Vienna',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Vilnius',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Europe/Volgograd',
		sdtOffset: 'UTC+03:00',
		sdtTzName: 'Moscow Time',
		sdtTzAbr: 'MSK',
	},
	{
		timeZoneId: 'Europe/Warsaw',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Zagreb',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Europe/Zaporozhye',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'Europe/Zurich',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Factory',
		sdtOffset: 'UTC+00:00',
		sdtTzName: '',
		sdtTzAbr: '-00',
	},
	{
		timeZoneId: 'GB',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'GB-Eire',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'GMT',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'GMT+0',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'GMT-0',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'GMT0',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Greenwich',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Hongkong',
		sdtOffset: 'UTC+08:00',
		sdtTzName: 'Hong Kong Time',
		sdtTzAbr: 'HKT',
	},
	{
		timeZoneId: 'HST',
		sdtOffset: 'UTC−10:00',
		sdtTzName: 'Hawaiian Standard Time',
		sdtTzAbr: 'HST',
	},
	{
		timeZoneId: 'Iceland',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Greenwich Mean Time',
		sdtTzAbr: 'GMT',
	},
	{
		timeZoneId: 'Indian/Antananarivo',
		sdtOffset: 'UTC+03:00',
		sdtTzName: 'East Africa Time',
		sdtTzAbr: 'EAT',
	},
	{
		timeZoneId: 'Indian/Chagos',
		sdtOffset: 'UTC+06:00',
		sdtTzName: '',
		sdtTzAbr: '+06',
	},
	{
		timeZoneId: 'Indian/Christmas',
		sdtOffset: 'UTC+07:00',
		sdtTzName: '',
		sdtTzAbr: '+07',
	},
	{
		timeZoneId: 'Indian/Cocos',
		sdtOffset: 'UTC+06:30',
		sdtTzName: '',
		sdtTzAbr: '+0630',
	},
	{
		timeZoneId: 'Indian/Comoro',
		sdtOffset: 'UTC+03:00',
		sdtTzName: 'East Africa Time',
		sdtTzAbr: 'EAT',
	},
	{
		timeZoneId: 'Indian/Kerguelen',
		sdtOffset: 'UTC+05:00',
		sdtTzName: '',
		sdtTzAbr: '+05',
	},
	{
		timeZoneId: 'Indian/Mahe',
		sdtOffset: 'UTC+04:00',
		sdtTzName: '',
		sdtTzAbr: '+04',
	},
	{
		timeZoneId: 'Indian/Maldives',
		sdtOffset: 'UTC+05:00',
		sdtTzName: '',
		sdtTzAbr: '+05',
	},
	{
		timeZoneId: 'Indian/Mauritius',
		sdtOffset: 'UTC+04:00',
		sdtTzName: '',
		sdtTzAbr: '+04',
	},
	{
		timeZoneId: 'Indian/Mayotte',
		sdtOffset: 'UTC+03:00',
		sdtTzName: 'East Africa Time',
		sdtTzAbr: 'EAT',
	},
	{
		timeZoneId: 'Indian/Reunion',
		sdtOffset: 'UTC+04:00',
		sdtTzName: '',
		sdtTzAbr: '+04',
	},
	{
		timeZoneId: 'Iran',
		sdtOffset: 'UTC+03:30',
		sdtTzName: '',
		sdtTzAbr: '+0330',
	},
	{
		timeZoneId: 'Israel',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Israel Standard Time',
		sdtTzAbr: 'IST',
	},
	{
		timeZoneId: 'Jamaica',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'Japan',
		sdtOffset: 'UTC+09:00',
		sdtTzName: 'Japanese Standard Time',
		sdtTzAbr: 'JST',
	},
	{
		timeZoneId: 'Kwajalein',
		sdtOffset: 'UTC+12:00',
		sdtTzName: '',
		sdtTzAbr: '+12',
	},
	{
		timeZoneId: 'Libya',
		sdtOffset: 'UTC+02:00',
		sdtTzName: 'Eastern European Time',
		sdtTzAbr: 'EET',
	},
	{
		timeZoneId: 'MET',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Mexico/BajaNorte',
		sdtOffset: 'UTC−08:00',
		sdtTzName: 'Pacific Standard Time',
		sdtTzAbr: 'PST',
	},
	{
		timeZoneId: 'Mexico/BajaSur',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'Mexico/General',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'MST',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'MST7MDT',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'Navajo',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'NZ',
		sdtOffset: 'UTC+12:00',
		sdtTzName: 'New Zealand Standard Time',
		sdtTzAbr: 'NZST',
	},
	{
		timeZoneId: 'NZ-CHAT',
		sdtOffset: 'UTC+12:45',
		sdtTzName: '',
		sdtTzAbr: '+1245',
	},
	{
		timeZoneId: 'Pacific/Apia',
		sdtOffset: 'UTC+13:00',
		sdtTzName: '',
		sdtTzAbr: '+13',
	},
	{
		timeZoneId: 'Pacific/Auckland',
		sdtOffset: 'UTC+12:00',
		sdtTzName: 'New Zealand Standard Time',
		sdtTzAbr: 'NZST',
	},
	{
		timeZoneId: 'Pacific/Bougainville',
		sdtOffset: 'UTC+11:00',
		sdtTzName: '',
		sdtTzAbr: '+11',
	},
	{
		timeZoneId: 'Pacific/Chatham',
		sdtOffset: 'UTC+12:45',
		sdtTzName: '',
		sdtTzAbr: '+1245',
	},
	{
		timeZoneId: 'Pacific/Chuuk',
		sdtOffset: 'UTC+10:00',
		sdtTzName: '',
		sdtTzAbr: '+10',
	},
	{
		timeZoneId: 'Pacific/Easter',
		sdtOffset: 'UTC−06:00',
		sdtTzName: '',
		sdtTzAbr: '-06',
	},
	{
		timeZoneId: 'Pacific/Efate',
		sdtOffset: 'UTC+11:00',
		sdtTzName: '',
		sdtTzAbr: '+11',
	},
	{
		timeZoneId: 'Pacific/Enderbury',
		sdtOffset: 'UTC+13:00',
		sdtTzName: '',
		sdtTzAbr: '+13',
	},
	{
		timeZoneId: 'Pacific/Fakaofo',
		sdtOffset: 'UTC+13:00',
		sdtTzName: '',
		sdtTzAbr: '+13',
	},
	{
		timeZoneId: 'Pacific/Fiji',
		sdtOffset: 'UTC+12:00',
		sdtTzName: '',
		sdtTzAbr: '+12',
	},
	{
		timeZoneId: 'Pacific/Funafuti',
		sdtOffset: 'UTC+12:00',
		sdtTzName: '',
		sdtTzAbr: '+12',
	},
	{
		timeZoneId: 'Pacific/Galapagos',
		sdtOffset: 'UTC−06:00',
		sdtTzName: '',
		sdtTzAbr: '-06',
	},
	{
		timeZoneId: 'Pacific/Gambier',
		sdtOffset: 'UTC−09:00',
		sdtTzName: '',
		sdtTzAbr: '-09',
	},
	{
		timeZoneId: 'Pacific/Guadalcanal',
		sdtOffset: 'UTC+11:00',
		sdtTzName: '',
		sdtTzAbr: '+11',
	},
	{
		timeZoneId: 'Pacific/Guam',
		sdtOffset: 'UTC+10:00',
		sdtTzName: 'Chamorro Time Zone',
		sdtTzAbr: 'ChST',
	},
	{
		timeZoneId: 'Pacific/Honolulu',
		sdtOffset: 'UTC−10:00',
		sdtTzName: 'Hawaiian Standard Time',
		sdtTzAbr: 'HST',
	},
	{
		timeZoneId: 'Pacific/Johnston',
		sdtOffset: 'UTC−10:00',
		sdtTzName: 'Hawaiian Standard Time',
		sdtTzAbr: 'HST',
	},
	{
		timeZoneId: 'Pacific/Kanton',
		sdtOffset: 'UTC+13:00',
		sdtTzName: '',
		sdtTzAbr: '+13',
	},
	{
		timeZoneId: 'Pacific/Kiritimati',
		sdtOffset: 'UTC+14:00',
		sdtTzName: '',
		sdtTzAbr: '+14',
	},
	{
		timeZoneId: 'Pacific/Kosrae',
		sdtOffset: 'UTC+11:00',
		sdtTzName: '',
		sdtTzAbr: '+11',
	},
	{
		timeZoneId: 'Pacific/Kwajalein',
		sdtOffset: 'UTC+12:00',
		sdtTzName: '',
		sdtTzAbr: '+12',
	},
	{
		timeZoneId: 'Pacific/Majuro',
		sdtOffset: 'UTC+12:00',
		sdtTzName: '',
		sdtTzAbr: '+12',
	},
	{
		timeZoneId: 'Pacific/Marquesas',
		sdtOffset: 'UTC−09:30',
		sdtTzName: '',
		sdtTzAbr: '-0930',
	},
	{
		timeZoneId: 'Pacific/Midway',
		sdtOffset: 'UTC−11:00',
		sdtTzName: 'Samoa Standard Time',
		sdtTzAbr: 'SST',
	},
	{
		timeZoneId: 'Pacific/Nauru',
		sdtOffset: 'UTC+12:00',
		sdtTzName: '',
		sdtTzAbr: '+12',
	},
	{
		timeZoneId: 'Pacific/Niue',
		sdtOffset: 'UTC−11:00',
		sdtTzName: '',
		sdtTzAbr: '-11',
	},
	{
		timeZoneId: 'Pacific/Norfolk',
		sdtOffset: 'UTC+11:00',
		sdtTzName: '',
		sdtTzAbr: '+11',
	},
	{
		timeZoneId: 'Pacific/Noumea',
		sdtOffset: 'UTC+11:00',
		sdtTzName: '',
		sdtTzAbr: '+11',
	},
	{
		timeZoneId: 'Pacific/Pago_Pago',
		sdtOffset: 'UTC−11:00',
		sdtTzName: 'Samoa Standard Time',
		sdtTzAbr: 'SST',
	},
	{
		timeZoneId: 'Pacific/Palau',
		sdtOffset: 'UTC+09:00',
		sdtTzName: '',
		sdtTzAbr: '+09',
	},
	{
		timeZoneId: 'Pacific/Pitcairn',
		sdtOffset: 'UTC−08:00',
		sdtTzName: '',
		sdtTzAbr: '-08',
	},
	{
		timeZoneId: 'Pacific/Pohnpei',
		sdtOffset: 'UTC+11:00',
		sdtTzName: '',
		sdtTzAbr: '+11',
	},
	{
		timeZoneId: 'Pacific/Ponape',
		sdtOffset: 'UTC+11:00',
		sdtTzName: '',
		sdtTzAbr: '+11',
	},
	{
		timeZoneId: 'Pacific/Port_Moresby',
		sdtOffset: 'UTC+10:00',
		sdtTzName: '',
		sdtTzAbr: '+10',
	},
	{
		timeZoneId: 'Pacific/Rarotonga',
		sdtOffset: 'UTC−10:00',
		sdtTzName: '',
		sdtTzAbr: '-10',
	},
	{
		timeZoneId: 'Pacific/Saipan',
		sdtOffset: 'UTC+10:00',
		sdtTzName: 'Chamorro Time Zone',
		sdtTzAbr: 'ChST',
	},
	{
		timeZoneId: 'Pacific/Samoa',
		sdtOffset: 'UTC−11:00',
		sdtTzName: 'Samoa Standard Time',
		sdtTzAbr: 'SST',
	},
	{
		timeZoneId: 'Pacific/Tahiti',
		sdtOffset: 'UTC−10:00',
		sdtTzName: '',
		sdtTzAbr: '-10',
	},
	{
		timeZoneId: 'Pacific/Tarawa',
		sdtOffset: 'UTC+12:00',
		sdtTzName: '',
		sdtTzAbr: '+12',
	},
	{
		timeZoneId: 'Pacific/Tongatapu',
		sdtOffset: 'UTC+13:00',
		sdtTzName: '',
		sdtTzAbr: '+13',
	},
	{
		timeZoneId: 'Pacific/Truk',
		sdtOffset: 'UTC+10:00',
		sdtTzName: '',
		sdtTzAbr: '+10',
	},
	{
		timeZoneId: 'Pacific/Wake',
		sdtOffset: 'UTC+12:00',
		sdtTzName: '',
		sdtTzAbr: '+12',
	},
	{
		timeZoneId: 'Pacific/Wallis',
		sdtOffset: 'UTC+12:00',
		sdtTzName: '',
		sdtTzAbr: '+12',
	},
	{
		timeZoneId: 'Pacific/Yap',
		sdtOffset: 'UTC+10:00',
		sdtTzName: '',
		sdtTzAbr: '+10',
	},
	{
		timeZoneId: 'Poland',
		sdtOffset: 'UTC+01:00',
		sdtTzName: 'Central European Time',
		sdtTzAbr: 'CET',
	},
	{
		timeZoneId: 'Portugal',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Western European Time',
		sdtTzAbr: 'WET',
	},
	{
		timeZoneId: 'PRC',
		sdtOffset: 'UTC+08:00',
		sdtTzName: 'China Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'PST8PDT',
		sdtOffset: 'UTC−08:00',
		sdtTzName: 'Pacific Standard Time',
		sdtTzAbr: 'PST',
	},
	{
		timeZoneId: 'ROC',
		sdtOffset: 'UTC+08:00',
		sdtTzName: 'China Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'ROK',
		sdtOffset: 'UTC+09:00',
		sdtTzName: 'Korean Standard Time',
		sdtTzAbr: 'KST',
	},
	{
		timeZoneId: 'Singapore',
		sdtOffset: 'UTC+08:00',
		sdtTzName: '',
		sdtTzAbr: '+08',
	},
	{
		timeZoneId: 'Turkey',
		sdtOffset: 'UTC+03:00',
		sdtTzName: '',
		sdtTzAbr: '+03',
	},
	{
		timeZoneId: 'UCT',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Coordinated Universal Time',
		sdtTzAbr: 'UTC',
	},
	{
		timeZoneId: 'Universal',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Coordinated Universal Time',
		sdtTzAbr: 'UTC',
	},
	{
		timeZoneId: 'US/Alaska',
		sdtOffset: 'UTC−09:00',
		sdtTzName: 'Alaskan Standard Time',
		sdtTzAbr: 'AKST',
	},
	{
		timeZoneId: 'US/Aleutian',
		sdtOffset: 'UTC−10:00',
		sdtTzName: 'Hawaiian Standard Time',
		sdtTzAbr: 'HST',
	},
	{
		timeZoneId: 'US/Arizona',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'US/Central',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'US/East-Indiana',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'US/Eastern',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'US/Hawaii',
		sdtOffset: 'UTC−10:00',
		sdtTzName: 'Hawaiian Standard Time',
		sdtTzAbr: 'HST',
	},
	{
		timeZoneId: 'US/Indiana-Starke',
		sdtOffset: 'UTC−06:00',
		sdtTzName: 'Central Standard Time',
		sdtTzAbr: 'CST',
	},
	{
		timeZoneId: 'US/Michigan',
		sdtOffset: 'UTC−05:00',
		sdtTzName: 'Eastern Standard Time',
		sdtTzAbr: 'EST',
	},
	{
		timeZoneId: 'US/Mountain',
		sdtOffset: 'UTC−07:00',
		sdtTzName: 'Mountain Standard Time',
		sdtTzAbr: 'MST',
	},
	{
		timeZoneId: 'US/Pacific',
		sdtOffset: 'UTC−08:00',
		sdtTzName: 'Pacific Standard Time',
		sdtTzAbr: 'PST',
	},
	{
		timeZoneId: 'US/Samoa',
		sdtOffset: 'UTC−11:00',
		sdtTzName: 'Samoa Standard Time',
		sdtTzAbr: 'SST',
	},
	{
		timeZoneId: 'UTC',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Coordinated Universal Time',
		sdtTzAbr: 'UTC',
	},
	{
		timeZoneId: 'W-SU',
		sdtOffset: 'UTC+03:00',
		sdtTzName: 'Moscow Time',
		sdtTzAbr: 'MSK',
	},
	{
		timeZoneId: 'WET',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Western European Time',
		sdtTzAbr: 'WET',
	},
	{
		timeZoneId: 'Zulu',
		sdtOffset: 'UTC+00:00',
		sdtTzName: 'Coordinated Universal Time',
		sdtTzAbr: 'UTC',
	},
] as const);
