name: Auto Publish to NPM

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write # Grant read and write access to read repo and create releases
    id-token: write # Grant access to GitHub token for authentication

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            # Install pnpm first to avoid 'pnpm not found' error
            - name: Install PNPM
              run: npm install -g pnpm

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: 'https://registry.npmjs.org/'
                  cache: 'pnpm'

            - name: Install Dependencies
              run: pnpm install --frozen-lockfile --store-dir ~/.pnpm-store

            - name: Publish to NPM
              run: pnpm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            # Extract version from package.json
            - name: Get version from package.json
              id: get_version
              run: |
                  VERSION=$(jq -r .version package.json)
                  echo "VERSION=${VERSION}" >> $GITHUB_ENV

            # Create a Git tag with the version
            - name: Create Git Tag
              run: |
                  git tag v${{ env.VERSION }}
                  git push origin v${{ env.VERSION }}

            # Create GitHub Release
            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: 'v${{ env.VERSION }}'
                  name: 'Version ${{ env.VERSION }}'
                  body: |
                      Find in [NPM Registry](https://www.npmjs.com/package/nhb-toolbox).
                      Full Docs at [Official Docs](https://nhb-toolbox.vercel.app)
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use GitHub token for authentication
