name: Auto Publish to NPM

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write # Grant read and write access to read repo and create releases
    id-token: write # Grant access to GitHub token for authentication

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            # Install pnpm first to avoid 'pnpm not found' error
            - name: Install PNPM
              run: npm install -g pnpm

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: 'https://registry.npmjs.org/'
                  cache: 'pnpm'

            - name: Install Dependencies
              run: pnpm install --frozen-lockfile --store-dir ~/.pnpm-store

            - name: Publish to NPM
              run: pnpm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            # Create a Git tag for the release
            - name: Create Git Tag
              id: create_git_tag
              run: |
                  VERSION=$(node -p "require('./package.json').version")
                  echo "VERSION=$VERSION"
                  git tag "v$VERSION"
                  git push origin "v$VERSION"

            # Create GitHub Release
            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: 'v${{ steps.create_git_tag.outputs.VERSION }}' # Reference the correct version tag
                  release_name: 'Release v${{ steps.create_git_tag.outputs.VERSION }}' # Optional: You can add a release name
                  body: |
                      This is an automatically created release for version ${{ steps.create_git_tag.outputs.VERSION }}.
                      You can update the description if necessary.
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use GitHub token for authentication
