name: Auto Publish to NPM

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write
    id-token: write

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install PNPM
              run: npm install -g pnpm

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: 'https://registry.npmjs.org/'
                  cache: 'pnpm'

            - name: Install Dependencies
              run: pnpm install --frozen-lockfile --store-dir ~/.pnpm-store

            # Get the current version from package.json
            - name: Get version from package.json
              id: get_version
              run: |
                  VERSION=$(jq -r .version package.json)
                  echo "VERSION=${VERSION}" >> $GITHUB_ENV

            # Get the latest Git tag (fetch first to ensure remote tags are available)
            - name: Get latest Git tag
              id: get_latest_tag
              uses: WyriHaximus/github-action-get-previous-tag@v1
              with:
                  fallback: 1.0.0

            # Compare versions and skip if same
            - name: Check if version changed
              id: check_version
              run: |
                  if [ "v${{ env.VERSION }}" = "${{ steps.get_latest_tag.outputs.tag }}" ]; then
                      echo "VERSION_UNCHANGED=true" >> $GITHUB_ENV
                  else
                      echo "VERSION_UNCHANGED=false" >> $GITHUB_ENV
                  fi

            # Publish only if version is different
            - name: Publish to NPM
              if: env.VERSION_UNCHANGED == 'false'
              run: pnpm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            # Create a Git tag if version is different
            - name: Create Git Tag
              if: env.VERSION_UNCHANGED == 'false'
              run: |
                  git tag v${{ env.VERSION }}
                  git push origin v${{ env.VERSION }}

            # Create GitHub Release if version is different
            - name: Create Release
              if: env.VERSION_UNCHANGED == 'false'
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: 'v${{ env.VERSION }}'
                  name: 'Version ${{ env.VERSION }}'
                  body: |
                      Find in [NPM Registry](https://www.npmjs.com/package/nhb-toolbox).
                      Full Docs at [Official Docs](https://nhb-toolbox.vercel.app)
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
